### PR TITLE
Robots Style Guide

### PR DESCRIPTION
**Pull request by Nnooo**
I have started creating a Robots Style guide and importing the already created Robots.

I think it is worth continuing this to ensure that all of the created Robots are actually useable not only from an aesthetic point of view but also from a consistency point of view.

If you cannot use them along side each other due to proportions, colours, line thickness etc not being consistent this will create issues.

### CODE REVIEW

**Comment by owocki** [comment]
Thanks @Nnooo !! @PixelantDesign curious what you think of this directionally

**Comment by Nnooo** [comment]
Here are some better examples of the difference.

robots_bender_main
robots_bender_prime
robots_bufficorn_main
robots_bufficorn_prime
robots_regulus_divine
robots_regulus_main
robots_regulus_prime


These have all been formatted to have the same line thickness, conform to the main, prime and divine naming (where appropriate) and fit within consistent size boxes for those types.

I cannot add this to the work I have done and submit the pull request for these new changes until you approve the previous ones,

**Comment by Nnooo** [comment]
Using the above should make it super simple to do anything you like with. If you scale them (with vector scaling on) they will all scale to keep the proportions and formatting making posters, web views etc much easier.

**Comment by owocki** [comment]
i like where this is headed @Nnooo 

i know you're in convos with myself and @PixelantDesign , let me know how to price the work you've done so far (since we were paying per artwork, not for a style guide), and we can go from there

**Comment by Nnooo** [comment]
Trying to juggle our slack and github convos ha ha!

I’d suggest pay by hour for this work as I am adjusting the artwork others have created? I checked in 2hes of work and have another 3hrs to check in to get the above all checked in. 

Then more hours for any additional changes.

**Pull request merged**
