### PR TITLE
Gitcoin Bots Kudos - Hippy bot

### PR DESCRIPTION
**Pull request by nasehim7**
image
This is my contribution towards https://github.com/gitcoinco/web/issues/4483

### CODE REVIEW

**Comment by owocki** [comment]
can we remove the gitcoin helmet from the bottom middle and instead put it along the bottom right edge (similar to the existing svgs in the creative repo)?

**Comment by nasehim7** [comment]
Updated image now Kevin:
image

**Comment by owocki** [comment]
ref image: http://bits.owocki.com/8c3726fb51a4/Image%202019-05-30%20at%201.39.15%20PM.png

looks a little stretched. can we fix the stretch and remove the helmet?

**Comment by nasehim7** [comment]
Made the changes, here is the image for reference:
image

**Pull request merged**
