### PR TITLE
Add new robots

### PR DESCRIPTION
**Pull request by emiwatanabe422**
Add Narwhal robot, C3P0 style robot, and Star Trek federation uniformed gitbot.

https://github.com/gitcoinco/web/issues/3712

image

image

image

### CODE REVIEW

**Comment by owocki** [comment]
cc @PixelantDesign for her feedback

**Comment by owocki** [comment]
I LOVE LOVE LOVE C-3PO and the narwhal :)  

For the Trekkey bot, I wonder if we could illongate his body more.. or if theres a way to make it more clear he is from the star trek universe ( http://bits.owocki.com/2f791441c1e4/Screen%20Shot%202019-02-23%20at%201.52.18%20PM.png ) 

i wonder if we can give him spock ears http://bits.owocki.com/47324787d62d/Screen%20Shot%202019-02-23%20at%201.52.50%20PM.png

**Comment by owocki** [comment]
for C-3PO what if we gave him the gitcoin bot-style eyes (two [green eyes](http://bits.owocki.com/d6470b30edcc/Screen%20Shot%202019-02-23%20at%201.57.35%20PM.png) instead of blue/white eyes)

**Comment by emiwatanabe422** [comment]
@owocki 
Thanks for the feedback! Let me know what you think:

image

image

**Comment by owocki** [comment]
i think it looks good.  one tiny nitpick, can the star trek logo on the star trek bot be an ether logo instead of a gitcoin one?

**Comment by owocki** [comment]
@PixelantDesign any feedback on this thread let us know!

**Comment by owocki** [comment]
@emiwatanabe422 can we add a pink ETH logo at the top of the narwhals' horn, like this bufficorn bot has? http://bits.owocki.com/b09ba413e0ca/Screen%20Shot%202019-02-24%20at%201.16.17%20PM.png

**Comment by emiwatanabe422** [comment]
@owocki 
No problem!
I went with the simpler eth logo found on the avatar clothing, let me know if that's alright. Also, added the sparkles for the narwhal one.

image

image

**Comment by owocki** [comment]
@emiwatanabe422 perfect :) 

can you update the SVGS on the pull request and i will merge / payout?

**Comment by emiwatanabe422** [comment]
@owocki 
Okay, files have been updated. 
I also added the pythonbot I made for the gitcoin ads bounty. So you guys can have it just as a robot svg file. (no need to pay out for that one)

image

**Comment by owocki** [comment]
@emiwatanabe422 you're my hero.   how much do i owe ya? 

want to make a few more bots? i like your work and would like to continue working with u

btw, i like your new avatar!

**Comment by emiwatanabe422** [comment]
@owocki Aww, thanks Steve! Yeah, I'll make more bots!
For now you owe me 125 DAI.

**Pull request merged**
