### PR TITLE
Bot Elmo

### PR DESCRIPTION
**Pull request by charlie4biz**
@owocki I finally created a bot Elmo, take a look. You can ignore the previous works I did.

### CODE REVIEW

**Comment by charlie4biz** [comment]
elmo
@owocki Here is the png. I already included the svg file on the last PR I did.

**Comment by charlie4biz** [comment]
BigBird Bot
bigbird

**Comment by owocki** [comment]
my primary concern with the bigbird bot is that his head looks too much like the copyrighted one.  all artwork needs to be completely original

**Comment by charlie4biz** [comment]
Ok. Will recreate it .

**Comment by charlie4biz** [comment]
Recreated the head of Bigbird
bigbird

It's like I am not getting any reward for the first Elmo with gitcoin helmet and the gitcoin helmet behind a laptop?

**Comment by owocki** [comment]
bird bot looks cool.  a lot of whitespace on his body tho.

happy to pay out both

**Comment by charlie4biz** [comment]
Will add feather-like pattern on the body. Can I do one more bot?

**Comment by charlie4biz** [comment]
bigbird

**Comment by charlie4biz** [comment]
oscar
Oscar Trash Can. :-)
That's the last. Sorry if I went over the 2 bots/person required. Just wanted to do this.

**Comment by owocki** [comment]
looking good. @PixelantDesign any feedback?

**Comment by charlie4biz** [comment]
@owocki seems others have been paid since 4days ago but I haven't and I submitted a week ago. Total of 5 bots now. Elmo, Big Bird, Oscar, Rick, and Morty.

**Comment by owocki** [comment]
thanks, can you please update the PR with the ones that are merge-able?    once its merged i can pay out

**Comment by charlie4biz** [comment]
Deleted the rejected ones. So we have just Elmo, Big Bird, Oscar, Rick, and Morty in the PR

**Comment by charlie4biz** [comment]
@owocki any update on payment.

**Pull request merged**
