### PR TITLE
Gandalf Inspired Bot

### PR DESCRIPTION
**Pull request by nasehim7**
I have added Gitcoin Bot creatives inspired by Gandalf

**Tackling:** gitcoinco/web#3712

**Demo:**

Gandalf:

image

@owocki your review this one

### CODE REVIEW

**Comment by nasehim7** [comment]
I made all the inspired bots in such a way that they don't distort the present bot blueprint and also get the character on it smoothly. I can change a lot but this is a challenge I wanted to take to get it on the present one.

**Comment by owocki** [comment]
im tickled pink, i think it looks like a really good start! 
- can he have two eyes, similar to [pika bot](https://github.com/gitcoinco/creative/blob/master/Marketing/Art/Robots/robot_kudos/kudos/pika_bot.svg)s eyes?
- can his cape be a bit more dynamic than just a flat color?  i like what you did with the wizard cap (having two colors)

**Comment by nasehim7** [comment]
@owocki Sure Sure Kevin. Just let me know how is this cape:

image

**Comment by nasehim7** [comment]
The Final touch:

image

**Comment by nasehim7** [comment]
Also @owocki, I have made this Harry Inspired Bot, let me know your take:

image

**Comment by owocki** [comment]
new gandalf looks great!  please update the PR with the SVG

harry potter, i never watched harry potter so i can't tell as much that its him!  but still cool; pls PR to the repo.  maybe we can do somethin gto give him a "glow" (or to give his wand a 'glow' ? )to show that hes magic?

**Comment by nasehim7** [comment]
Updated Harry:

image

I will update the PR in a moment

**Pull request merged**
