### PR TITLE
Add Statue of Liberty bots

### PR DESCRIPTION
**Pull request by GuistF**
statue_of_liberty6

### CODE REVIEW

**Comment by owocki** [comment]
this looks like it deletes a file, not adds one?

**Comment by GuistF** [comment]
in fact, I had added the two models and later I saw that you prefer the first bot. So I removed the second one

**Comment by GuistF** [comment]
but if you prefer I can add it again.

**Comment by GuistF** [comment]
plz, tell me if I need to do something more

**Comment by GuistF** [comment]
Thank you, tell me if you need anything.  I will be happy to help!

**Comment by owocki** [comment]
another 'love bot' or 'heart bot' (as seen in the existing repo) would be cool.

the juxtaposition of a robot learning to love is kind of cool :)

**Comment by GuistF** [comment]
Ok, I will do it  :)

**Pull request merged**
