### PR TITLE
Add new Japanese style bots

### PR DESCRIPTION
**Pull request by GuistF**
Hi! here are some bots for evaluation. I hope you like! 
japanese_kudos

### CODE REVIEW

**Comment by owocki** [comment]
im way into 2 and 3!

**Comment by GuistF** [comment]
ok, I  tried to put some Japanese elements o the first one. I may have to make some changes and reduce the illustration to just one element.

**Comment by GuistF** [comment]
First boy sketch with kaiju fighting. @owocki  Can you tell me what you think, please?
kaiju_fighting

**Comment by owocki** [comment]
i love it !

**Comment by GuistF** [comment]
@owocki Thanks, I created a Koi fish bot too :)
Koi_Fish

**Comment by owocki** [comment]
also love it

**Pull request merged**
