### PR TITLE
Gitcoin Bots Kudos - Halo Inspired

### PR DESCRIPTION
**Pull request by nasehim7**
image

Adding Halo towards gitcoinco/web#4483

### CODE REVIEW

**Comment by owocki** [comment]
thx.  whats the smoke coming off his mask?

**Comment by nasehim7** [comment]
@owocki It is more of like the mask is getting constructed from the arrangement of the smoke. Just a different touch to the original Halo mask or else it would have been very basic is what I felt, so made this. Similar how this is: https://www.youtube.com/watch?v=NiSmlmn1ezQ

Appearing from smoke, the nightcrawler effect :D

**Comment by owocki** [comment]
@nasehim7 shoot i just accidenlty merged.  reverting now

**Comment by owocki** [comment]
@nasehim7 is the artwork in this original?  it looks a little close to the original artwork

**Comment by nasehim7** [comment]
@owocki Yes I have sketched it on Procreate. It is on the similar lines but not exact. Majorly you might be thinking like that because of the helmet.

**Comment by owocki** [comment]
oh ok thanks.

**Pull request merged**
