### PR TITLE
Gitcoin Bot Kudos - Elmo Inspired Bot

### PR DESCRIPTION
**Pull request by petitechoco**
Submitting an elmo bot towards https://github.com/gitcoinco/web/issues/4483

Screen Shot 2019-06-01 at 8 15 07 AM

### CODE REVIEW

**Comment by petitechoco** [comment]
@owocki What do you think?

Wish I saw Elmo being created here. Didn't intend to duplicate work: https://github.com/gitcoinco/creative/pull/90

**Comment by owocki** [comment]
purdy cool.   is the green part his eye, or are his eyes his eyes?

**Comment by petitechoco** [comment]
The actual mascot bot is wearing the Elmo suit. I didn't want to lose the aesthetics in your actual bot so got the inspiration of something as changing skins or costumes. Should I make some changes?

**Comment by owocki** [comment]
it just seems strange to me that he has two sets of eyes.  i'm not sure what we can do about it, but if you wouldnt mind spending 10 minutes playing around trying to solve that problem, i'd appreciate that.

**Comment by petitechoco** [comment]
Okay. Will make some changes and get back to you!

**Comment by petitechoco** [comment]
These are some variations that I came up with. Which path is the direction that you have in mind? If you can tell me I can elaborate more and refind them. 

Screen Shot 2019-06-03 at 8 27 03 AM

**Comment by owocki** [comment]
im partial to the 2nd and 3rd one.  

though now that im looking at 2/3 they kind of look a little bit too much like a copy and not just "inspired by" the original piece. i wonder if theres anythign we can do to make the bot's eyes or nose / head more robotic..

**Comment by petitechoco** [comment]
@owocki, what do you think?
Screen Shot 2019-06-03 at 9 04 17 AM

**Comment by owocki** [comment]
perfect -- mind updating hte svg on the PR?

**Pull request closed without merging**
