### PR TITLE
Create mario-bot.svg

### PR DESCRIPTION
**Pull request by uivlis**

### CODE REVIEW

**Comment by owocki** [comment]
is it a goomba or a mushroom? :) https://www.google.com/search?q=mario+mushroom&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj0w9nd3dLgAhUH4oMKHRXkAXMQ_AUIDigB&biw=1920&bih=946

**Comment by uivlis** [comment]
It's a mushroom 🍄

**Comment by owocki** [comment]
love it!  do you want to do another one? let me know if/when how much i owe you

**Comment by uivlis** [comment]
Sure, I'll do another one.

**Comment by uivlis** [comment]
Actually, I think I'm fine with just one design (I'm working on another bounty now).

**Comment by owocki** [comment]
cool cool how much do i owe you?

**Comment by uivlis** [comment]
35 DAI.

**Pull request merged**
