### PR TITLE
More bots

### PR DESCRIPTION
**Pull request by Virtual-Face**
@owocki Here are the three other robots. Yoda, Gandalf and Spongebob.
I'm working on the edits now.
Yoda
Gandalf
Spongebob

### CODE REVIEW

**Comment by owocki** [comment]
@Virtual-Face i LOVE all three! 

i wonder if they'd look better w. two eyes each, instead of one eye.  [check out this bot](https://github.com/gitcoinco/creative/blob/master/Marketing/Art/Robots/robot_kudos/kudos/pika_bot.svg) for an example

**Comment by Virtual-Face** [comment]
Let me work on the two eyes version, I'll upload the result.
Here are the edits from the previous ones. A more muscular hulk and I added more depth to the falcon.

Hulk-2
Millenuim-2

**Comment by owocki** [comment]
looks really good.  pls add the svgs to the PR!

**Comment by Virtual-Face** [comment]
Sure.
Here are the two eyes version. Which one do you like more?

Gandalf-B
Spongebob-B
Yoda-B

**Comment by owocki** [comment]
the spongebob one looks really good!  i think that yoda/gandalfbot need noses tho

**Comment by Virtual-Face** [comment]
I uploaded Spongebob SVG
What do you think about these?
Gandalf-C
Yoda-C

**Comment by owocki** [comment]
looks great! pls add the svgs and ill merge / payout

**Comment by Virtual-Face** [comment]
Uploaded, thanks.
I was thinking that I worked more movie characters than game characters, so I have few ideas for game characters that we can do.
Assassins Creed, Half-Life (Gordon Freeman), Pacman, Duck Hunt, Portal, Rayman, Lara Croft, Lego, Minecraft
Let me know if you want me to work on any of them.

**Comment by owocki** [comment]
@Virtual-Face Pacman, Duck Hunt, Lego, Minecraft sound interesting to me!

we were also considering dropping a bounty soon for some 90s themed bots soon.  some ideas:

Discman
Tamagotchi
Troll dolls
Cassette
Nokia snake game
Pogs
saved by the bell
slap bracelets
ninja turtles
walkman (think that’s also discman), pagers, floppy discs, PDA tablets, MS-DOS, chips challenge, minesweeper, dial up and DSL, ebaumsworld.

not all of them belong as bots.. i will write up a ticket with a full spec soon

**Comment by Virtual-Face** [comment]
Thanks for the payout.
That's great, waiting for the specs for that bounty. I'll work on these four bots until then.

**Comment by owocki** [comment]
ended up just posting two bounties for 90s theme-d stuff here

https://github.com/gitcoinco/kudosbadges/issues/191
https://github.com/gitcoinco/web/issues/3712 (this is the bot bounty, just thte desc has been updated)

one is for a 90s themed bot, one is for kudos

**Pull request merged**
