### PR TITLE
profile headers restored

### PR DESCRIPTION
**Pull request by writeprovidence**
@owocki , i just sent a PR containing the profile headers

### CODE REVIEW

**Comment by owocki** [comment]
:)

**Comment by owocki** [comment]
looks like i sent you 0.7 ETH on 2019-11-27 -- how much do i still owe ya? theres been a few PRs so im not exactly sure at this poihnt

**Comment by writeprovidence** [comment]
@owocki , yes you paid me 0.7 ETH for the BOT Creatives - Winter 2019

**Comment by writeprovidence** [comment]
The ETHDenver Die Cut Stickers bounty rules says $40 for per sticker. and i made three stickers. that should be $120. Thanks

**Comment by writeprovidence** [comment]
thanks for tips

**Pull request merged**
