### PR TITLE
Adding some new Bots

### PR DESCRIPTION
**Pull request by z737**
I have created Buzzlightyear Bot, Captain America Bot and Spoke bot

### CODE REVIEW

**Comment by z737** [comment]
CaptainAmerica Bot


Buzz_Lightyear_Bot (1)


SpockBot

**Comment by owocki** [comment]
very cool :) 

i wonder if the captain america inspired one is too close to the copyrighted one.

**Comment by z737** [comment]
About the copyright issue, i think some changes in the background and rotating the star in the shield do the thing. Do you have any suggestions?

**Comment by owocki** [comment]
yes that makes sense to me. 

 for the star trek inspired one, can we add a little background image behind the bot? similar to the other two (and the inspiration images for kudos)

**Pull request merged**
