### PR TITLE
Game bots

### PR DESCRIPTION
**Pull request by Virtual-Face**
@owocki Lego and Minecraft. What do you think?
I'm working on the other two and will upload them soon.
Lego
Minecraft

### CODE REVIEW

**Comment by owocki** [comment]
i like them both a lot!  i wonder what the minecraft one would look like with two eyes?  the combination of the human skin color (instead of bot arms) + one eye is creepy to me.

**Comment by Virtual-Face** [comment]
Sure, I'll try that.
Here are the other two bots. Pacman and Duck Hunt.
Pacman
Dock-Hunt

**Comment by Virtual-Face** [comment]
Here is the two eyes version for Minecraft
Minecraft-2

**Comment by owocki** [comment]
i like a lot! @PixelantDesign what do you think?

**Comment by Virtual-Face** [comment]
So should I upload the SVG for all of them?

**Comment by owocki** [comment]
yes pls

**Comment by Virtual-Face** [comment]
I checked  the updated list and there are some characters that I would like to work on.
darth vader, iron man, wonderwoman, superman, ninja turtles, donkey kong. Also we can pick some characters from mortal kombat and  street fighters if you are interested.

**Comment by owocki** [comment]
@Virtual-Face i'm excited about darth vader, wonderwoman, superman, ninja turtles, and donkey kong.

from mortal combat, i used to always play raiden + sub zero + scorpion!  what did you play?

**Comment by owocki** [comment]
also @Virtual-Face how much do i owe you? we have a few threads going and want to settle up all at onc

**Comment by Virtual-Face** [comment]
@owocki I start working on them.
I used to play all of them tbh :) 
Only this last PR (Lego, Minecraft, Pacman, Duck Hunk) , all the previous ones are settled.

**Pull request merged**
