### PR TITLE
diecut_stickers

### PR DESCRIPTION
**Pull request by writeprovidence**
@owocki , i just add three diecut sticker design for review pls take a look

### CODE REVIEW

**Comment by owocki** [comment]
do u have svgs for the stickers perchance?

why does this PR delete all those profile headers?

**Comment by writeprovidence** [comment]
yes i have svgs of the stickers

**Comment by writeprovidence** [comment]
I removed the profile headers from the repo, thought its no longer needed

**Comment by writeprovidence** [comment]
going to bring them back now

**Comment by writeprovidence** [comment]
@owocki i just brought back the profile header

**Comment by writeprovidence** [comment]
i wanted you to make review on the png format on the diecut_stickers , then i will send the final design as svg

**Comment by writeprovidence** [comment]
die cut01

**Comment by writeprovidence** [comment]
die cut-03

**Comment by writeprovidence** [comment]
die cut-02

**Comment by writeprovidence** [comment]
@owocki can we make reviews here?

**Comment by owocki** [comment]
as long as the PR contains the SVGs for the abvove screenshots, i think the stickers look good. still need to remove the profile header changes from the diff to get it merged tho

**Comment by writeprovidence** [comment]
okay, will send a PR with the svgs

**Pull request closed without merging**
