### PR TITLE
Thor Creative Bot

### PR DESCRIPTION
**Pull request by nasehim7**
I have added Gitcoin Bot creatives - Thor Inspired

**Tackling:** gitcoinco/web#3712

**Demo:**

Thor:

image

@owocki This is the Thor which I was talking about yesterday

### CODE REVIEW

**Comment by owocki** [comment]
purdy dope - can we add some circuits to [his chest](http://bits.owocki.com/40ce7336fca0/Screen%20Shot%202019-03-20%20at%209.29.13%20AM.png) so its not just dark blue?

**Comment by nasehim7** [comment]
@owocki Thanks Kevin! Update: 
image

**Comment by owocki** [comment]
sweet -- whats our current tally that i owe you?

**Comment by nasehim7** [comment]
@owocki  I was updating the commit and the same moment this PR got merged so the change did not get through Kevin

**Pull request merged**
