### PR TITLE
Yoda Creative Bot

### PR DESCRIPTION
**Pull request by nasehim7**
I have added Gitcoin Bot creatives inspired by Yoda

**Tackling:** gitcoinco/web#3712

**Demo:**

Yoda:

image

@owocki your review on this one as well

### CODE REVIEW

**Comment by owocki** [comment]
i think it looks really good! can we change the color of the light saber to be more neon green instead of forrest green? [screenshot](http://bits.owocki.com/d9d770f239ac/Screen%20Shot%202019-03-10%20at%2011.29.36%20AM.png)

**Comment by nasehim7** [comment]
@owocki How is this one Kevin:

image

**Comment by owocki** [comment]
LGTM!

**Comment by nasehim7** [comment]
Thanks Kevin, I will update the PR then :D

**Pull request merged**
