### PR TITLE
Minion Inspired Bot

### PR DESCRIPTION
**Pull request by z737**
Minion_Bot

Happy Minion holding Banana

### CODE REVIEW

**Comment by owocki** [comment]
LGTM; @PixelantDesign ?

**Comment by owocki** [comment]
wait why is he holding a banana?  i googled 'minions banana' and didnt see anything banana-ey for minions?

did you mean to attach the other svgs (buzz bot, captain america bot) to this?

**Comment by z737** [comment]
Minions love Bananas. Throughout the movie, whenever they see bananas, they get distracted and try to go for the bananas. I've attached some reference images for this.

Oops, I will delete the other svgs from here and upload them onto the other pull request.
download (1)
MIN01WH
MV5BMzMwYjc1N2MtY2U2Ny00MTc3LTk1YWQtYzE3NmM5NWQ2YzkyXkEyXkFqcGdeQXVyMzAzODY0NzE@ _V1_UX182_CR0,0,182,268_AL_

**Comment by owocki** [comment]
ok makes sense to me.  let me know when the PR is updated with just having the minion bot and we can take it from there

**Comment by z737** [comment]
updated the pull request.

**Pull request merged**
