### PR TITLE
AquaMan and Captain Gitcoin Creative Bot

### PR DESCRIPTION
**Pull request by nasehim7**
I have added AquaMan and Captain Gitcoin creative bot

**Tackling:** gitcoinco/web#3712

**Demo:**

Aquaman:

image

Captain Gitcoin:

image

@owocki Let me know your take on these. Last PR for this issue this month :D

### CODE REVIEW

**Comment by owocki** [comment]
awesome!  whats my latest total up to / what do i owe ya

**Comment by nasehim7** [comment]
@owocki Thanks for the appreciation Kevin :D 
13 designs in total :)

**Comment by owocki** [comment]
got it; all priced at the robot bounty rate?

**Comment by nasehim7** [comment]
All of it is related to the bot issue which was raised this month, 3712 :) has bots and all the creative elements like tamagotchi, MS DOS etc.

**Pull request merged**
