### PR TITLE
Snowboarding GitCoinbot

### PR DESCRIPTION
**Pull request by nasehim7**
Added Snowboarding GitCoinBot

Artwork:
image

Issue: https://github.com/gitcoinco/web/issues/5465

### CODE REVIEW

**Comment by owocki** [comment]
border looks a little funny with the dropshadow.. otherwise i think it looks good

**Comment by nasehim7** [comment]
@owocki How about this, Kevin:

image

**Comment by nasehim7** [comment]
@owocki Kevin, I have submitted this one as well on kudos. This one can also be closed. :D

**Comment by owocki** [comment]
🙏

**Pull request merged**
