### PR TITLE
Gitbot R2D2 Avatar Submission

### PR DESCRIPTION
**Pull request by ATorbMain**

### CODE REVIEW

**Comment by ATorbMain** [comment]
Example Avatars Seen here: 
GitBotR2D2Sample1
GitBotR2D2Sample2

**Comment by owocki** [comment]
how does this look? anything to put in ur bio? 

https://gitcoin.co/onboard/profile?steps=avatar&theme=starbot

**Comment by ATorbMain** [comment]
Looks great! As for my bio, "A designer and coder from the United States, always looking to learn more and help others!"

**Comment by ATorbMain** [comment]
A pleasure to make this one for you!

**Pull request merged**
