### PR TITLE
Die Cut Stickers 2

### PR DESCRIPTION
**Pull request by nasehim7**
Added Die Cut Sticker for:

1) Not your Not your keys, not your coins
image

2) ETH is money
image

3) BUIDL your Tribe
image

Issue: #159 

@owocki Hope you like it :D

### CODE REVIEW

**Comment by owocki** [comment]
1 and 2 are missing a bot.. and just look like a sign..

3. looks good directionally but the gitcoin logo is discoloured..  i think that it'd look better if you didnt do that... and maybe dropped the color scheme in the text box to be more neutral (also why is the text box an oval? were you trying to make a speech box? seeems like its not efficiently using space around the text.. )

**Comment by nasehim7** [comment]
@owocki For the 1st and 2nd, I made them keeping the elements minimum and including the Gitcoin logo to put the Gitcoiny feel in it by transforming the "O" in the first one and putting the gitcoin logo above the equal sign showing this is "Gitcoin Equation" for the second. Should we change it?
For the third one, yes having a more neutral color would be great. I didn't think about it as a speechBox but yes lets try doing that and also cut down on spaces. Lets see how it turns out to be. I will post the samples soon and if you will like it then will update the PR. :)

**Comment by nasehim7** [comment]
@owocki What do you think about this, Kevin?

image

**Comment by owocki** [comment]
looking good!  one issue: i worry that the font isnt big enough for peoiple to be able to read it.... maybe if we put the text up on the hat it would scale up?

**Comment by nasehim7** [comment]
@owocki I have revised the stickers:
image

image

image

**Comment by owocki** [comment]
love it :)

**Comment by nasehim7** [comment]
I have updated the PR Kevin, you can merge it :)

**Pull request merged**
