### PR TITLE
bufficorn ethDenver 2019

### PR DESCRIPTION
**Pull request by nasehim7**
Adding Bufficorn travelling in the snow to reach ETH Denver Kudos

Artwork:
image

Issue: https://github.com/gitcoinco/web/issues/5465

### CODE REVIEW

**Comment by owocki** [comment]
lgtm

**Comment by nasehim7** [comment]
@owocki Thanks a lot :D

**Comment by nasehim7** [comment]
@owocki I can see the winter design bounty is cancelled now. Is this one and the other PR good to be merged?

**Comment by owocki** [comment]
yes!  can u submit it at gitcoin.co/kudos/new pls and ill merge

**Comment by nasehim7** [comment]
@owocki Submitted it Kevin

**Pull request merged**
