### PR TITLE
Adding some Rick and Morty new Bots 

### PR DESCRIPTION
**Pull request by petitechoco**
I have created Rick and Morty themed new bots.

Screen Shot 2019-06-06 at 11 43 35 AM
Screen Shot 2019-06-06 at 12 16 37 PM
Screen Shot 2019-06-06 at 12 16 28 PM

### CODE REVIEW

**Comment by owocki** [comment]
i like them a lot! 

is it possible to have a background image that frames the bots, like the reference designs have?

@PixelantDesign what do you think?

**Comment by petitechoco** [comment]
@owocki I can fix the bg. Will upload sketches soon 👍

**Comment by petitechoco** [comment]
@owocki how's the bg? Was this something that you had in mind?
Screen Shot 2019-06-07 at 10 58 44 AM

**Comment by owocki** [comment]
perfect!  can you update the diff on the pull request pls? 

also can u add the dogbot one (as long as it's completely original)? that one is fun!

**Comment by petitechoco** [comment]
@owocki, please check. I have updated it

**Pull request merged**
