### PR TITLE
PDA | Slap Belt Design

### PR DESCRIPTION
**Pull request by nasehim7**
I have added Gitcoin Bot creatives - PDA and Slap Belt Bots

**Tackling:** gitcoinco/web#3712

**Demo:**

PDA:

image

Slap Belt:

image

@owocki let me know how these are :D

### CODE REVIEW

**Comment by owocki** [comment]
hard to tell the slap bracelet is a slap bracelet. almost looks like a hammer, which is cool too!

**Comment by nasehim7** [comment]
I thought of it like one hand slapping the belt over the other but yeah you are right. I made this small edit to show the slap effect:

image

@owocki Kevin Let me know how this looks like

**Comment by nasehim7** [comment]
Also, I wanted to know how does the PDA look with that shadow around :D

**Comment by owocki** [comment]
looking at this to remember how slap bracelets work lol! https://images.vat19.com/covers/large/vat19-slap-bracelet.jpg

i think that whats throwing me off is that the robot arms don't look like hands, and therefore it's hard to tell thats what this is.  two directions i could see us going

1. add a "slap!" in this style ( http://bits.owocki.com/fa9ddb4249a5/Screen%20Shot%202019-03-18%20at%2010.13.44%20AM.png ) to the image
2) make the hands into real hands (hopefully not creepy hands) so that its clear what it is to the viewer.  and maybe show the slap bracelet wrapping around the other side of the wrist

**Comment by nasehim7** [comment]
Improvisation:
image

**Comment by owocki** [comment]
PDA looks great!

SLAP -> can we make the font a little bit more comic bookey?

**Comment by nasehim7** [comment]
Sure Sure Kevin, I will update here in a while with the new look :D

**Comment by nasehim7** [comment]
Maybe this time on point:

image

@owocki Kevin up for review

**Comment by owocki** [comment]
looks great - thanks for the revs!

**Comment by owocki** [comment]
let me know when you want to settle up!

**Comment by owocki** [comment]
happy to fold in multiple PRs together if u want

**Comment by nasehim7** [comment]
@owocki Would like to review this one as well: https://github.com/gitcoinco/creative/pull/58

Once reviewed, you can settle up all these 7 new designs which I have uploaded recently :D

**Comment by nasehim7** [comment]
And Thanks for the appreciation Kevin, means a lot :D

**Pull request merged**
