### PR TITLE
Japanese Art Ninja Bot

### PR DESCRIPTION
**Pull request by nasehim7**
This is the Gitcoin Japanese Art version from my side. The character written is gitcoin in Kanji. Hope you like it @owocki

Tackling: gitcoinco/web#5089

Image for reference:
image

### CODE REVIEW

**Comment by owocki** [comment]
thanks nasehim.  is the ninja art original / liscensed for this purpose? 

also what is this yellow thing? http://bits.owocki.com/a96c1f3afa4d/Image%202019-09-01%20at%207.20.21%20AM.png

**Comment by nasehim7** [comment]
@owocki Yes I have made everything. The yellow thing is depicting light from above like the way you can see here:
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwichd22gbDkAhUM148KHeTYAhcQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.videoblocks.com%2Fvideo%2Fgolden-heaven-light-rays-from-above-soft-optical-lens-flares-shiny-animation-art-background---new-quality-natural-lighting-lamp-rays-shiny-effect-dynamic-colorful-holiday-bright-video-footage-rwk6mg8pzjgnqogvg&psig=AOvVaw1OI_Yo0oZa7TXph7m1UtjB&ust=1567440605696700

**Comment by danlipert** [comment]
Hey @nasehim7 ーcan you write the katakana characters as "ギットコイン" instead? I think its a more accurate translation. Also, can you remove the mirrored characters? Thanks!

**Comment by nasehim7** [comment]
Hey @danlipert, I have fixed it now. is it looking fine now:

image

**Comment by danlipert** [comment]
@nasehim7 nice! looks good!

**Pull request merged**
