### PR TITLE
Added juggerbot and looney-bot

### PR DESCRIPTION
**Pull request by uivlis**
With no particular connection, I designed two new bots/styles: one resembles the 70's cartoons, the other, a player hero (Juggernaut) from Defense of the Ancients. Don't worry about copyrights, in the first case, it's all my design, and in the second case, the outline was downloadable from a print-and-color website.

What do you think @owocki ? 

Also, I have a small request: in the past, I see that all the kudos I designed were minted at an address which does not belong to me. I also see that now you requested us to personally submit the kudos, so I will change for now that address to the one which actually belongs to me (which is the default address from gitcoin). But, for the future, I kindly ask from you, in the case that I will design any more kudos, for you to mint them at my default address from my gitcoin profile (@uivlis).

### CODE REVIEW

**Comment by owocki** [comment]
regarding the designs.. i think that theres too much of a contrast of the fighter's head and their body... one looks super bot-ey and the other looks super organic

for the looney toons one; its missing the look/feel of the tiny toons logo (https://www.google.com/search?q=tiny+toons+logo&tbm=isch&source=iu&ictx=1&fir=Sejwd7GM8SX4NM%253A%252CveXx7oE7-bM1gM%252C_&vet=1&usg=AI4_-kS8yVI7BaG7R9oaAMDDcRGbeDc7mQ&sa=X&ved=2ahUKEwi_8M31p_TlAhVFqZ4KHUSkCB0Q9QEwBHoECAQQIQ#imgrc=Sejwd7GM8SX4NM: ) which i would ascribe as more colorful and has a feeling or togetherness that this one lacks.  also the 'adventures' in the original artwork kind of balances out the top and button of the logo

>  But, for the future, I kindly ask from you, in the case that I will design any more kudos, for you to mint them at my default address from my gitcoin profile

I'm happy to do this.. but I can't pay as much DAI for them if they are owned by you (because then every purchase will have to go to your address, and because of that.. we can't use them as airdrops). let me know which way you'd like it

**Comment by uivlis** [comment]
> I'm happy to do this.. but I can't pay as much DAI for them if they are owned by you (because then every purchase will have to go to your address, and because of that.. we can't use them as airdrops). let me know which way you'd like it

Got it, I thought it was a mistake, but in that case, sure, I'd like them minted at whichever address you wish, as long as I still get paid.

> for the looney toons one; its missing the look/feel of the tiny toons logo (https://www.google.com/search?q=tiny+toons+logo&tbm=isch&source=iu&ictx=1&fir=Sejwd7GM8SX4NM%253A%252CveXx7oE7-bM1gM%252C_&vet=1&usg=AI4_-kS8yVI7BaG7R9oaAMDDcRGbeDc7mQ&sa=X&ved=2ahUKEwi_8M31p_TlAhVFqZ4KHUSkCB0Q9QEwBHoECAQQIQ#imgrc=Sejwd7GM8SX4NM: ) which i would ascribe as more colorful and has a feeling or togetherness that this one lacks. also the 'adventures' in the original artwork kind of balances out the top and button of the logo

I was thinking more about this logo, not the tiny toons one: https://www.google.com/search?q=looney+tunes+original+logo&sxsrf=ACYBGNTXpwy-Pd2MvcHnFaauaDLHE0rzLg:1574099682745&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjuh7mjqvTlAhUE-yoKHRLyBegQ_AUIESgB&biw=1853&bih=928#imgrc=zxjbdCtDLmUQSM which doesn't have the 'adventures' bottom tagline, nor a colorful or communitarian outlook. Would this be fine, then?

> i think that theres too much of a contrast of the fighter's head and their body... one looks super bot-ey and the other looks super organic

Sure, I will adjust that.

**Comment by owocki** [comment]
got it makes sense. (on both accounts)

for the warrior one.. im pretty sure that people who arent dota fans wont understand this.. im not a DOTA fan so i can't say if DOTA fans will get it

**Comment by uivlis** [comment]
Yeah, I think they will! Juggernaut is one of the most beloved character from the game. Surely they will spot the correspondence.

**Comment by owocki** [comment]
kewl kewl - submit to gitcoin.co/kudos/new and ill accept the PR

**Comment by uivlis** [comment]
Done!

**Comment by uivlis** [comment]
@owocki I think you forgot to pay me for this one, can you accept my submitted work?

**Pull request merged**
