### PR TITLE
Added Contributor and Funder page

### PR DESCRIPTION
**Pull request by justpixel**
Reference: https://github.com/gitcoinco/web/issues/1672

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@justpixel @PixelantDesign good for merge?

**Comment by owocki** [comment]
@PixelantDesign @justpixel @thelostone-mc 139 changed files ... i think something went wrong here there should just be two new additions.. contributor and funder page

**Comment by PixelantDesign** [comment]
The Ghost of Github. These files have already been merged. @owocki @thelostone-mc, it's showing for me in creative repo.

**Comment by owocki** [comment]
yes.. they've already been merged, and that is the source of the missing files in the main repo.. 

check the diff tab, this is the PR where many files unrelated to the stated scope of this PR were deleted

**Comment by owocki** [comment]
@justpixel can you please restore the 100s of lost files from this PR?  you can see which ones were inadvertedly removed [here](https://github.com/gitcoinco/creative/pull/18/files)

**Comment by owocki** [comment]
ok; since no one seems to be willing to take ownership of fixing this problem, which was *clearly* introduced via this PR ( https://github.com/gitcoinco/creative/pull/18/files ) , ill do it.  7544ca4f32f507b02ad8fcbeabfb96c00308a8d8

**Pull request merged**
