### PR TITLE
New Noir Bot SVG

### PR DESCRIPTION
**Pull request by excerebrose**
Related to this https://github.com/gitcoinco/web/issues/5089
Developed new artwork.

### CODE REVIEW

**Comment by owocki** [comment]
omg so cool!

**Comment by excerebrose** [comment]
Hey @owocki, since I did this through gitcoin, and I'm glad you love it, how do I go ahead availing the bounty & producing more work along it?

**Comment by owocki** [comment]
@excerebrose i just paid you out; if you want to continue working on more items, then please go ahead!  we have a special need for more japanese style artwork since devcon V is gonna be in osaka japan this year.

**Comment by excerebrose** [comment]
@owocki I shall get crackin on that today itself :)

**Pull request merged**
