### PR TITLE
Giutcoin Zoom Background

### PR DESCRIPTION
**Pull request by cryptonautica**

### CODE REVIEW

**Comment by cryptonautica** [comment]
I also created a second options with the mission.

Thanks!

[Gitcoin-Zoom-Background (1).mp4.zip](https://github.com/gitcoinco/creative/files/4559490/Gitcoin-Zoom-Background.1.mp4.zip)

**Comment by owocki** [comment]
thanks @cryptonautica i have a few more asks for you.  will hit u up on gitcoin chat

**Comment by owocki** [comment]
derp cant find u on gitcoin chat

**Comment by cryptonautica** [comment]
Can't login to gitcoin chat for some reason.

**Comment by owocki** [comment]
hmm mind creating a github issue at https://github.com/gitcoinco/web letting us know what u see?

**Comment by cryptonautica** [comment]
Done #6538

**Pull request merged**
