### PR TITLE
Towards the top Gitcoin Bot

### PR DESCRIPTION
**Pull request by nasehim7**
This is the Gitcoin Snow version(towards the top) from my side. Hope you like it @owocki 

Tackling: gitcoinco/web#5089

Image for reference:

image

### CODE REVIEW

**Comment by owocki** [comment]
what does 'towards the top' mean?  

any way to add some definition to the mountains? they just look like white blobs right now

**Comment by nasehim7** [comment]
It is somewhat like always progressing. Always heading to reach heights in things - If you understand what I mean
If you don't like it we can remove it. Yes I will add more definition to the mountains :D

**Comment by nasehim7** [comment]
@owocki I haven't updated the PR but have changed the artwork. For your reference:

image

If you like it I will then change the PR. Let me know your take on this :)

**Comment by owocki** [comment]
i think it looks good.

**Comment by nasehim7** [comment]
@owocki Kevin Updated the PR with the same now :D

**Pull request merged**
