### PR TITLE
Pixel Kudos

### PR DESCRIPTION
**Pull request by L-KH**

### CODE REVIEW

**Comment by owocki** [comment]
mind posting a screenshot? i cant seem to preview these in browser

**Comment by L-KH** [comment]
@owocki , Oh sorry my bad. I edit it hope it works now. if it works should I mint it in Gitcoin?

**Comment by owocki** [comment]
sure!

**Comment by owocki** [comment]
pls submit via gitcoin.co/requestmoney + gitcoin.co/kudos/new if u've not already + ill get it paid out and minted

**Pull request merged**
