### PR TITLE
Wonder woman and Donkey Kong

### PR DESCRIPTION
**Pull request by Virtual-Face**
New bots. What do you think @owocki ?
DonkeyKong
Wonderwoman

### CODE REVIEW

**Comment by owocki** [comment]
so cool :) 

asking the core team for feedback now.  will circle back (and if i dont, pls remind me in 2 days or so)

**Comment by Virtual-Face** [comment]
Here are my last works since you're closing this bounty.
How are they?
Leonardo:
Leonardo
Raphael:
Raphael
Donatello:
Donatello
Michelangelo:
Michelangelo

**Comment by owocki** [comment]
looks great!  whats the latest / how much do i owe ya?

**Comment by Virtual-Face** [comment]
Happy you liked it.
There is this current PR and #66 PR to settle.

**Comment by Virtual-Face** [comment]
@owocki Since you said I remind you in 2 or 3 days, this PR and the #66 are still unpaid.

**Comment by owocki** [comment]
@Virtual-Face how much do i owe ya?

**Comment by Virtual-Face** [comment]
8 bots which is 280 DAI if I'm right

**Pull request merged**
