### PR TITLE
added two gradient bots

### PR DESCRIPTION
**Pull request by dvdptr**
adding two bots with gradient fills as special edition for kudos, discussed in #5465

### CODE REVIEW

**Comment by owocki** [comment]
thanks; looks good. ill mint them now.. still trying to figure out how to pay these out given they are derivative works...

**Comment by owocki** [comment]
@dvdptr tips are fine.. i still havent figured out how to price the "fork"ed ones tho.. the bounty was meant for new artworks.. what do you think is fair

**Comment by dvdptr** [comment]
@owocki ok now I get it – well I'm happy with whatever you are fine to give. took me like an hour to finalize for each one, so what about a total of .5 eth matching your lowest offer at ~35 sai per robot with a little tip on top? :)

**Comment by dvdptr** [comment]
@owocki great, thanks! (btw I've also send PR for the die cut stickers)

**Pull request merged**
