### PR TITLE
BatMan and SuperMan Creative Bot

### PR DESCRIPTION
**Pull request by nasehim7**
I have added Gitcoin Bot creatives inspired by Batman and Superman

Tackling: gitcoinco/web#3712

image
image

Hope you guys like it @owocki

### CODE REVIEW

**Comment by owocki** [comment]
very cool!  

sending to the gitcoin team for feedback.  for now, my only item of feedback is that it'd be cool if the body of the bots was a little taller.. it kind of looks funny that their midsection is only 10% of the height of the frame.

**Comment by nasehim7** [comment]
Hahahha true but actually I didn't want to mess up the original bot flavour so yeah this thing. I think it would bring more Gitcoiny(I know that there is no word like that) touch to it 😍 @owocki

**Comment by owocki** [comment]
feel free to take liberties with the gitcoin bot ([heres](https://github.com/davmey/gitcoin/blob/master/pika.jpg) an example where the bot was completely changed )

**Comment by nasehim7** [comment]
Sure @owocki 
Thinking of making Cyborg and robocop inspired bot
https://www.google.com/search?biw=1440&bih=821&tbm=isch&sa=1&ei=5b98XKLaHMfvrQGStpSgCw&q=cyborg+teen+titans&oq=cyborg+teen+titans&gs_l=img.3...1550.6058..6228...1.0..0.147.1615.0j13......1....1..gws-wiz-img.......35i39j0i67j0.0q2zDn-VbTw#imgrc=0FOpZC0VSnIfUM:

and

https://www.google.com/search?biw=1440&bih=821&tbm=isch&sa=1&ei=7L98XMrFFJC3rQHC8YKIDg&q=robocop&oq=robocop&gs_l=img.3..35i39j0i67l3j0j0i67j0l2j0i67j0.22058.23312..24298...0.0..0.128.855.0j7......1....1..gws-wiz-img.DhC6MIIcvnU#imgrc=nCeBCtDELpLieM:

**Comment by owocki** [comment]
@nasehim7 both seem like good ideas to me!

**Comment by owocki** [comment]
@nasehim7 lets do it!

**Pull request merged**
