### PR TITLE
mr meeseeks bot added

### PR DESCRIPTION
**Pull request by mehul0698**
@owocki hey kevin I was not getting any idea for the sesame st. bot. I have added a Mr. meeseeks bot from rick and morty, just check it out and let me know.
image

### CODE REVIEW

**Comment by mehul0698** [comment]
@owocki This year we have the cricket world cup which is a very big event in india and it is being played in england so I have made a cricket inspired bot.
image

**Comment by owocki** [comment]
both look cool :)

for the meeseeks one, is the box original?  we can only accept original art + i want to make sure thats not pasted from anywehere

**Comment by mehul0698** [comment]
image

**Comment by mehul0698** [comment]
@owocki I have made a side view of the box and added a gitcoin logo at the centre to make it look more authentic.

**Comment by mehul0698** [comment]
image

**Comment by mehul0698** [comment]
@owocki I have changed the colour scheme of the box and removed the octagon at the centre to make it look less like the original so that it does not appear copied.

**Pull request merged**
