### PR TITLE
newBots Cassette | Discman | Floppy | Tamagotchi

### PR DESCRIPTION
**Pull request by nasehim7**
I have added Gitcoin Bot creatives - Cassette, Discman, Floppy, Tamagotchi

**Tackling:** gitcoinco/web#3712

**Demo:**

Cassette:
image

Discman:
image

Floppy:
image

Tamagotchi:
image

### CODE REVIEW

**Comment by nasehim7** [comment]
@owocki let me know your take on these :D

**Comment by owocki** [comment]
i like them a lot.  if theres a way to fit a gitcoin logo and maybe "grow open source" on the cassette and  floppy disk, thatd be great.

**Comment by nasehim7** [comment]
@owocki These are the samples Kevin:

image

image

If you think it's fine, let me know I will update the SVGs as well

**Comment by nasehim7** [comment]
Updated the SVGs as well just to be consistent in case you like it you can right away merge it :D

**Comment by owocki** [comment]
i think they're a little small relative to the size of the art piece.  maybe just the visual mark of the helmet would suffice on both; as the text will be illegible at most sizes this is printed

**Comment by nasehim7** [comment]
How about this Kevin:

image

image

I lighten the Gitcoin logo on the Cassette sort of like a watermark and for the second one I posted it as a bigger one.

**Comment by owocki** [comment]
floppy disk looks good to me.

for the cassette, lets put the logo front and center on the top of the cassette and remove the transparency

**Comment by nasehim7** [comment]
Like this one: https://github.com/gitcoinco/creative/pull/58#issuecomment-474094818

For the cassette :)

Also I have made a thor bot, will be uploading in a while :D

**Comment by owocki** [comment]
yeah like that one, just without the 'grow open source' in small font on the bottom

**Comment by nasehim7** [comment]
Updated the PR @owocki :D

**Comment by nasehim7** [comment]
@owocki Thanks, I have uploaded 7 designs Kevin. :D and you have been paying around 40$s for each one so 7*40 = 280$s

**Comment by owocki** [comment]
got it; theres 4 on this PR.  and the other 3 are ninja turtle, pda, slap belt right?

hmm.. i should probably form another bounty for the non-bot artwork that gets generated as https://github.com/gitcoinco/web/issues/3712 is specifically scoped / priced for bots

**Comment by nasehim7** [comment]
@owocki Yes Kevin! Yeah that would be great. My PRs are a mix and match at the moment but contains  ideas mentioned in the issue: https://github.com/gitcoinco/web/issues/3712

**Comment by owocki** [comment]
got it; so i can judge the complexity of the non-bot artwork -- is it more, less, or the same work as a standard bot?

**Comment by nasehim7** [comment]
@owocki Frankly saying Kevin it is how much effort one puts in, like the floppy one was easy then the Cassette (this was similar to a bots effort) then Discman then the tamagotchi, they all take on an average same kind of an effort which I put in a bot. Talking about Thor, it took like the same amount of time which I put in 3 bots combined. So it is totally on how much smaller elements one puts in and thinking done. I won't say it less or more, instead I would say same would suffice. :D

**Comment by owocki** [comment]
just paid ya on the other thread

**Comment by nasehim7** [comment]
Yes I checked now, Thanks Kevin for the payment :D

**Pull request merged**
