### PR TITLE
Gitcoin Spray Bot

### PR DESCRIPTION
**Pull request by nasehim7**
This is another artwork from my side - GitBot spraying Gitcoin all over the city. Hope you like it @owocki

Tackling: gitcoinco/web#5089

Image for reference:

image

### CODE REVIEW

**Comment by owocki** [comment]
what a vandalous bot!!  

i wonder if we should have the bot spray paint the logo according to brand guidelines... or just go in another direction alltogether.. maybe have it spray paint #SustainOSS instead?

**Comment by nasehim7** [comment]
Kevin I like the idea of #SustainOSS. Also we can do #GrowOSS as well, what do you think? Both of them suit me :D

**Comment by owocki** [comment]
lets do #SustainOSS

**Comment by nasehim7** [comment]
Kevin Let me know if you like this:

image

I will update the PR accordingly

**Comment by owocki** [comment]
lgtm

**Comment by nasehim7** [comment]
Updated the PR Kevin :D

**Comment by nasehim7** [comment]
Hey Kevin, Are we still on with more bots?

**Comment by owocki** [comment]
whatd you want to do next? i am mostly prioritizing devcon / japan ones now

**Comment by nasehim7** [comment]
If that is the case I will focus my artwork on those lines :D

**Pull request merged**
