### PR TITLE
Devcon V Epic Gaiju against Astrobots

### PR DESCRIPTION
**Pull request by excerebrose**
Hey @owocki hope you're well, sorry it took me two days to get this in, I wanted something more epic like the movies, so here we have another classic Gaiju Monster (went for extreme detail) over tokyo skyline with multiple astroboy inspired bots there to save the day.

Image attached for reference.
Let me know what you think!
Gaiju-astrobot

### CODE REVIEW

**Comment by owocki** [comment]
woah cool!  its kind of hard to see bc the artwork is so dark..but looks like thats by design?

all artwork is original and/or liscensed for our use right?

**Comment by excerebrose** [comment]
that's what I wanted to go for, can tone the brightness up a wee bit if you'd like.
Everything is custom made by me, hence the 2 day period, so yes good to use by you and your team!

**Comment by excerebrose** [comment]
@owocki  brighter version here
Gaiju-astrobot-brighter

**Comment by owocki** [comment]
looks great! wanna update PR and ill pay u out?

**Comment by excerebrose** [comment]
@owocki thanks! done!

**Pull request merged**
