### PR TITLE
Megaman_Zero_Megaman_Shooting_Kudos

### PR DESCRIPTION
**Pull request by JollyRogerz**
Megaman Zero and Megaman Shooting kudos

### CODE REVIEW

**Comment by owocki** [comment]
very cool! can you submit to gitcoin.co/kudos/new too

**Comment by JollyRogerz** [comment]
Yes sure can

A quinta, 2/04/2020, 17:19, Kevin Owocki <notifications@github.com>
escreveu:

**Comment by JollyRogerz** [comment]
@owocki  I have minted both kudos, i see that megaman shooting is already available but the image is not loading correctly, when i open the svg it opens correctly, bt for some reason the kudos online is not showing megaman, could it be because of the image having two layers ? I can put everything on the same layer and see if it solves the problem

**Comment by owocki** [comment]
should we fixed now

**Comment by JollyRogerz** [comment]
Awesome, I see both are appearing like they should now :D Just for
curiosity sake what was the error ? xP

**Comment by owocki** [comment]
we try to convert all the SVGS to png for preview images, but this one didnt convert successfully so im just telling the system to use the SVG as the preview

**Comment by JollyRogerz** [comment]
<3

**Comment by owocki** [comment]
pls submit via gitcoin.co/requestmoney + gitcoin.co/kudos/new if u've not already + ill get it paid out and minted

**Pull request merged**
