### PR TITLE
adding bot

### PR DESCRIPTION
**Pull request by kvndlgs**
I created, following the style guide, a bot inspired on ED209 from Robocop and big hero 6.

let me know if there's anything I need to change.

ED209_1

bighero6

shovelbot

Well, I"m not sure in which universe I was when I've read the briefing at first, but here's another one, 
 Shoveling is hardly the best part of winter. 😳

adding trickybot

trickybot_1

### CODE REVIEW

**Comment by nasehim7** [comment]
Hey @kvndlgs 
Great to have your contribution! It would be awesome if you can post/attach your creative JPEG or PNG in the description as It would help the reviewer to understand how it looks.

Thanks

**Comment by kvndlgs** [comment]
@nasehim7 Absolutely, I'm on it. Thank you.

**Comment by kvndlgs** [comment]
@owocki

**Comment by owocki** [comment]
looks good - submit them at gitcoin.co/kudos/new and ill accept/merge

**Comment by kvndlgs** [comment]
i've submitted them few weeks ago

**Comment by kvndlgs** [comment]
@owocki thanks

**Pull request merged**
