### PR TITLE
Scam Bot

### PR DESCRIPTION
**Pull request by Virtual-Face**
Hey @owocki . What do you think about this evil scambot? For quest enemies

Scambot

### CODE REVIEW

**Comment by Virtual-Face** [comment]
Sorry, forgot to ask before working on this, but since you asked for snow sport themed designs ans since Christmas is near, I thought maybe Christmas/snow theme might be a good one. Let me know what you think. Since I didn't ask before start, I can work on something else and drop this one.

Christmas

**Comment by owocki** [comment]
xmas one looks cool!.. maybe a quick santa outside of the window would be kewl :)

scambot looks good as a quest enemy!

**Comment by Virtual-Face** [comment]
Santa added

Christmas-06-01

**Comment by owocki** [comment]
looks good! wanna submit on gitcoin.co/kudos/new and update the PR?

**Comment by Virtual-Face** [comment]
Great, just uploaded.
Do you want me to work on two more?

**Comment by owocki** [comment]
yes!  would be interested in having a submission from you on https://gitcoin.co/issue/gitcoinco/creative/159/3716

**Pull request merged**
