### PR TITLE
Git Omniac Kudos

### PR DESCRIPTION
**Pull request by omnianalytics**
Here is our submission to the KUDOS BOT Creatives - Summer 2020 edition. Let us know if you like it!

### CODE REVIEW

**Comment by owocki** [comment]
looks great :)

**Comment by omnianalytics** [comment]
Public view

gitty_pixelized

**Comment by omnianalytics** [comment]
> looks great :)

Thanks!

**Comment by omnianalytics** [comment]
Looks like we need to export as svg. We'll do that for the final submission through:  https://gitcoin.co/kudos/new

**Comment by omnianalytics** [comment]
Final submitted .svg version.  The version in the pull request is .png, which supports mesh gradients.  This version was slightly altered for compatibility:

image

**Comment by owocki** [comment]
pls submit via gitcoin.co/requestmoney + gitcoin.co/kudos/new if u've not already + ill get it paid out and minted

**Pull request merged**
