### PR TITLE
Create you're-not-perfect.svg

### PR DESCRIPTION
**Pull request by uivlis**
The nightmare from Courage the Cowardly Dog.
Ok, I did do something naughty, I changed the colors of the Regulus bot, but it was for art's sake.

### CODE REVIEW

**Comment by owocki** [comment]
for flintstones-bot.svg -- the body of the bot looks just like flintstones.  we can only accept original artwork unfortuantely, i dont want to cause a copyright claim against either of us... maybe you could make the body from scratch as a bot?

i had to google 'courage the cowardly dog you're not perfect'; that one mostly LGTM tho!

**Comment by uivlis** [comment]
glad you like the "you're-not-perfect" thing. I uploaded something else, an octopus regulus. If you like that one also, maybe I can do one more?

**Comment by owocki** [comment]
nice; just checked it out.  i wonder if theres a way to make the octopus look more like the helmet in terms of style and robot-ness.  right now it just kind of looks like a helmet pasted on top of an octopus

**Comment by uivlis** [comment]
Hope it works now, I tried to make the octopus resemble the style and robotness of the helmet.

**Comment by owocki** [comment]
perf

**Pull request merged**
