### PR TITLE
Create morpheus_bot.svg

### PR DESCRIPTION
**Pull request by Virtual-Face**
morpheus_bot

### CODE REVIEW

**Comment by owocki** [comment]
can we make his face more bot-like?

btw what do you think of the design guidelines i posted in the bounty?  do they help or hurt you create something great? cc @PixelantDesign

**Comment by Virtual-Face** [comment]
@owocki  Yes, sure.
I think the guidelines are perfect for making the bots consistent in all the designs since different designers working on them. But I have two question about the colors. 
The outline color in the guideline is perfect for bright fill colors, but when the fill color is dark (like the Morpheus coat here) it blends and you can't really see the outline. So I think having one bright outline color is gonna help the design. But if you think one color is better, I will edit it here too.
My second question is about the color palette. The palette is great, but some characters need specific colors that are not in the pallet. For example, here, there is no color for using as skin color for Morpheus. I can use black but it's the same as the coat. So do you have any suggestion?

**Comment by owocki** [comment]
thanks for the thoughtful comments about the design guidelines.  im sort of out of my depth here tho.  just do what you think is best pls

**Comment by Virtual-Face** [comment]
I've edited the Morpheus bot.

morpheus_bot2

I also added Magneto bot. What do you think?

Magneto

**Comment by owocki** [comment]
magneto looks great

**Comment by Virtual-Face** [comment]
Thanks. 
Do you think Morpheus needs anything else?
I'm ready to design more bots if you want.

**Pull request merged**
