### PR TITLE
RoboMyth & Cyborg

### PR DESCRIPTION
**Pull request by nasehim7**
I have added Gitcoin Bot creatives inspired by Cyborg and Robocop with a Mythical touch

Tackling: gitcoinco/web#3712

**Inspiration:**
https://github.com/gitcoinco/creative/pull/44#issuecomment-469129863

**Demo:**

Cyborg:

image

RoboCop Mythical:

image

@owocki let me know how it is :D

### CODE REVIEW

**Comment by owocki** [comment]
I like them both.  Could you post inspiration images of what you were going for with both?

**Comment by owocki** [comment]
asking because i wasnt sure exactly what ar obocop mythical is and i couldnt find them on google images!

**Comment by nasehim7** [comment]
Hi Kevin
for the cyborg one: https://www.google.com/search?q=cyborg+teen+titans+go&source=lnms&tbm=isch&sa=X&ved=0ahUKEwii3MyUq_rgAhUD73MBHbF1AmEQ_AUIDigB&biw=1440&bih=821#imgrc=5hmf_wVB3pKjNM:

The Robocop one is a mix. There is no such thing like Robocop Mythical, I took the basic Robocop(which can be seen on the head of the bot) and put in some mythical touch to it like we have mythical creatures right using the blue and grey prints on it.

**Comment by owocki** [comment]
ahh okay; makes sense to me!

**Pull request merged**
