### PR TITLE
Add Independence Day Bots

### PR DESCRIPTION
**Pull request by GuistF**
independence_day

### CODE REVIEW

**Comment by owocki** [comment]
I asked a bunch of people what their feedback was and heres what they said
Screen Shot 2019-06-28 at 5 44 16 PM

maybe worth another iteration or two on kudos number 2?  ill pay for 2 more if u want to bring the total up to 5 :)

**Comment by GuistF** [comment]
I'm sorry I didn't understand, do you want me to make an alteration on the kudos number2?

**Comment by GuistF** [comment]
And that's Okay,  I will make more 2 kudos with the same theme.

**Comment by owocki** [comment]
> do you want me to make an alteration on the kudos number2

yeah!  if you have time.  if not, id jus taccept / tip this out now

**Comment by GuistF** [comment]
ok! I can do it

**Comment by owocki** [comment]
let me merge the existing ones.  hit me back when you've got more of the center-style ones

**Comment by GuistF** [comment]
Hey, I added some things in kudo number 2, as requested, you can see on the first image below. following the sketch for kudos number 4-Parade illustration and 5- picnic/barbecue.

4july

**Comment by owocki** [comment]
they all look great!  PR them and ill pay those out too

**Comment by GuistF** [comment]
Thank you, I already did the PR.https://github.com/gitcoinco/creative/pull/113

**Pull request merged**
