### PR TITLE
Add biking and camping bots

### PR DESCRIPTION
**Pull request by GuistF**
Gitcoin Bots

### CODE REVIEW

**Comment by owocki** [comment]
these are amazing.  thank you @GuistF !   any other outdoor activities (err activities...) you want to do next?  

@PixelantDesign any comments?

**Comment by GuistF** [comment]
awesome, maybe I can doing kayak, hiking or climbing bots

**Comment by PixelantDesign** [comment]
looks great! On the purple Kudos - Could we knock out the Gitcoin logo in all white and keep the letter O green?

**Comment by GuistF** [comment]
ok , like this
kd

**Comment by GuistF** [comment]
@PixelantDesign  did you saw the new version for Darth Vader bot https://github.com/gitcoinco/creative/pull/84  ? if it's ok, I'll update it along with this new change

**Pull request merged**
