### PR TITLE
Loki

### PR DESCRIPTION
**Pull request by Virtual-Face**
loki

### CODE REVIEW

**Comment by owocki** [comment]
melikes!  what does @PixelantDesign think!?

**Comment by Virtual-Face** [comment]
Spiderman
spiderman

**Comment by Virtual-Face** [comment]
Sonic
sonic-01

**Comment by owocki** [comment]
thanks :) these are cool.   do you have vector versions you can attach?

for sonic, i think he'd look a little less creepy with two eyes instead of one.  maybe could take some inspiration from [pika bot](http://bits.owocki.com/312f9d97e266/Screen%20Shot%202019-02-25%20at%2010.05.29%20AM.png)

**Comment by Virtual-Face** [comment]
I edited Sonic.
sonic-03


And sure, I will upload SVG format.

**Comment by owocki** [comment]
looks good! tag me when u do

**Comment by Virtual-Face** [comment]
Here is the SVG version

[Robots.zip](https://github.com/gitcoinco/creative/files/2905648/Robots.zip)

**Comment by Virtual-Face** [comment]
I wroked on two more robots

Here is Hello Kitty
hello kitty-01

**Comment by Virtual-Face** [comment]
And Batman

batman-02

**Comment by owocki** [comment]
for the batman one, i wonder if we make his one eye into two eyes that will reduce the whitespace.

design inspiration: [batman eyes](http://bits.owocki.com/8f71aaecc56e/Screen%20Shot%202019-02-26%20at%2010.10.09%20AM.png)

**Comment by owocki** [comment]
is there a way to add more kitty-style stuff ot the kitty style bot?

http://bits.owocki.com/18bfe74b54ee/Screen%20Shot%202019-02-26%20at%2010.12.24%20AM.png
http://bits.owocki.com/5c142462a9aa/Screen%20Shot%202019-02-26%20at%2010.12.40%20AM.png

**Comment by owocki** [comment]
for the spiderman one, is there a way to make him look more [like spiderman](http://bits.owocki.com/8d5de9a98889/Screen%20Shot%202019-02-26%20at%2010.13.20%20AM.png)? right now it just looks like we lazily added via a filter

**Comment by Virtual-Face** [comment]
@owocki  Sure, I will apply all the changes.
I tried to keep the original robot designs as much as I can, so after uploading them if you feel it needs more features from the characters, we can add them.

**Comment by owocki** [comment]
> I tried to keep the original robot designs

feel free to evolve such that it makes the individual piece look good :)

**Comment by Virtual-Face** [comment]
batman-04
spiderman-08-01
hello kitty-04

**Comment by owocki** [comment]
so dope! i love them :)

for the hello kitty one, it might make a little sense to make her eyes / face look a little more bot like (to the extent you can do it without making her look creepy).

other than that, i'm 👍 on this!  pls add the svgs to the PR!

**Comment by Virtual-Face** [comment]
Great. Happy that you liked them.
I've tried to make the hello kitty more bot like. Let me know if it's good.
hello kitty-07

**Comment by owocki** [comment]
sweet -- can you add the svgs to the PR and ill pay you out?

note: i'm going on vacay this afternoon, so it might take me a couple days to pay out if we don't wrap this up in the next few hours.  not urgent, just wanted you to know my timeline.

**Comment by Virtual-Face** [comment]
I uploaded all of them, SVG
I had few more ideas. Can I keep make more of them?

**Comment by owocki** [comment]
@Virtual-Face yes pls!  let me know what you had in mind

**Comment by Virtual-Face** [comment]
Thanks for the payout
I was thinking about working on these: Terminator, Matrix Themed, Indiana Jones, Harry Potter, Thor

**Comment by owocki** [comment]
Terminator, Matrix, Thor, and Bane seems really interesting to me!  I say go for it

**Comment by Virtual-Face** [comment]
Sure 👍  Here are Terminator and Thor. Let me know if they need anything.
I'm working on the next two.

terminator
thor

**Comment by owocki** [comment]
i love the thor one :)

with terminator, i wonder if theres an opportunity to make him half bot half man [img](http://bits.owocki.com/5f61fadc0cee/Screen%20Shot%202019-03-05%20at%201.57.59%20PM.png) -- can tip ya if that changes the scope / intricacy in a meaningful way!

**Comment by Virtual-Face** [comment]
I will work on Terminator and will show you the result.
Here are Bane and Agent Smith.

bane

agent-smith

**Comment by owocki** [comment]
i really like both of them.  can we maybe add a little bit of a background image ( like what we did with the grey circle [here](http://bits.owocki.com/1304c9998238/Screen%20Shot%202019-03-06%20at%2012.34.30%20PM.png)  to the agenet smith one?  i dont really like the light green backbround on it.

i wonder if theres a way to get a more green on black backgfround on it too. [examples](http://bits.owocki.com/d2b9ae47268f/Screen%20Shot%202019-03-06%20at%2012.34.58%20PM.png)

**Comment by Virtual-Face** [comment]
Great. Happy you liked them.
I edited Terminator and Matrix, so let me know what you think.

terminator-2
agent-smith-2

**Comment by owocki** [comment]
both look great!

can we submit a PR back to the repro with all the SVGS?

**Comment by Virtual-Face** [comment]
All the SVGs are submitted.
I have more ideas for more robots. Let me know if you liked me to continue working on them.

**Comment by owocki** [comment]
hey @Virtual-Face where did you submit them?  this PR is already merged so i can't re-merge it, can you submit another, new, PR for these assets?

i would LOVE to have you keep making more bots.  what ones do you want to do?

**Comment by Virtual-Face** [comment]
Sorry, made new PR now.
I think these bots can be fun:  Wolverin, Magneto, Hella, Yondu, Hulk, Spongebob, Gandalf, Millennium Falcon, Master Yuda
Which ones do you like me to work on?

**Comment by owocki** [comment]
I'd be excited about Hulk, Spongebob, Gandalf, Millenium Falcon (how are you gonna pull this one off lol?), Yoda

FYI there is a wolverine here :) https://github.com/gitcoinco/creative/blob/master/Marketing/Art/Robots/3rd_party/xmen_wolverine.svg

**Comment by Virtual-Face** [comment]
I was a little busy but finally got the time to start working on the new robots. Millennium Falcon and Incredible Hulk
How do they look?
Millenuim
Hulk

**Comment by owocki** [comment]
falcon looks good!  its a little flat in your image relative to how it looks [here](https://www.google.com/search?q=millennium+falcon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjo_qv9xfjgAhXI54MKHWi2BxEQ_AUIDigB&biw=720&bih=691&dpr=2) though. i donno if theres a way to give it deptH?

my first reaction to hulk bot is that he could use more muscles..  but then i thought 'how would one add muscles to a robot?  :P  would that request be incompatible with the art itself?

**Comment by owocki** [comment]
also, would you mind opening up a new PR everytime you create a new batch of robots?  just easier to track it that way IMHO

**Comment by Virtual-Face** [comment]
Sure I'll give it more depth.
About Hulk, I think I can add some kind of metal pieces as muscles. Will show you the result.
And yes, I will make a new PR next time I wanted to upload the designs.

**Pull request merged**
