### PR TITLE
Summer 2020 Kudos bot

### PR DESCRIPTION
**Pull request by melvinalvarez**
hello @owocki this is my first entry for the summer 2020 pixel art kudos, let me know what you think!

### CODE REVIEW

**Comment by nasehim7** [comment]
Hi @melvinalvarez 
Could you please post the image here as well so that community can see the preview. Thank you :D

**Comment by melvinalvarez** [comment]
> Hi @melvinalvarez
> Could you please post the image here as well so that community can see the preview. Thank you :D

Here you go, let me know what you guys think! 

Pixel01_melvinalvarez_pixel_bot_01 copy

**Comment by owocki** [comment]
love it :) awesome work!

**Comment by owocki** [comment]
pls submit, ill prob do the first batch of payouts this week

**Comment by melvinalvarez** [comment]
Here's the second one I managed to make, let me know what you think!

02_Discovery-07

**Comment by owocki** [comment]
@melvinalvarez looks good pls submit!

**Comment by owocki** [comment]
pls submit via gitcoin.co/requestmoney + gitcoin.co/kudos/new if u've not already + ill get it paid out and minted

**Pull request merged**
