### PR TITLE
samurai bot added

### PR DESCRIPTION
**Pull request by mehul0698**
Hey I have added a samurai bot.
image

### CODE REVIEW

**Comment by mehul0698** [comment]
The line is just the part of the screenshot. @owocki

**Comment by mehul0698** [comment]
Hey I have added a ramen eating bot. @owocki 
image

**Comment by owocki** [comment]
thanks mehul... i can't help but wonder what the samurai bot would look like with a little thinner lines, can we take a shot at that?

**Comment by mehul0698** [comment]
Hey @owocki I have updated the samurai bot.
image

**Comment by owocki** [comment]
looks good!  merging

**Comment by mehul0698** [comment]
@owocki I think you sent the tip to wrong account.

**Comment by owocki** [comment]
my mistake.  @nasehim7 mind returngin that tip to me, or sending directly to @mehul0698 ?

**Comment by nasehim7** [comment]
@owocki I will send it directly to @mehul0698 once the payment is confirmed. From where can I find his ETH Address? and the payment is 0.25000 ETH

**Comment by owocki** [comment]
@nasehim7 it's the address attached to your gitcoin account . the one listed on https://gitcoin.co/profile/nasehim7

**Comment by nasehim7** [comment]
@owocki Yes Kevin. I wanted mehul's address to send the payment

**Comment by mehul0698** [comment]
@nasehim7 0xb9c4668CEf8B52b1A0751Dcf14605Cd90F8c9Fce

**Comment by nasehim7** [comment]
@mehul0698 You can track it here: https://etherscan.io/tx/0x4d82fc17f3016f3c6ed0698d0bc6ec09946f0f4bb077c1a11b0748a33433d673

**Comment by nasehim7** [comment]
Also @mehul0698 to mention the ramen bot looks a little pixelated. Did you make it like that intentionally? @owocki Any thoughts on this?

**Comment by mehul0698** [comment]
@nasehim7 it's just the screenshot.

**Comment by nasehim7** [comment]
Oops my bad

**Comment by owocki** [comment]
thanks you both :)

**Pull request merged**
