### PR TITLE
unicorn / Gitcoin wallpaper

### PR DESCRIPTION
**Pull request by writeprovidence**

### CODE REVIEW

**Comment by writeprovidence** [comment]
new unicorn

**Comment by owocki** [comment]
@writeprovidence can you pls put these in a folder on https://github.com/gitcoinco/creative/tree/master/Marketing/Art/Robots called 'unicorn' ?

**Comment by writeprovidence** [comment]
ok will do that.

**Comment by owocki** [comment]
thanks!  if i owe you any tokens pls remind me how much!

**Pull request merged**
