### PR TITLE
Noodle Fighter

### PR DESCRIPTION
**Pull request by Virtual-Face**
Hi @owocki 
Here is Noodle Fighter, my first design. A mighty fighter with a touch from modern Japanese art. (and he loves hot noodles) 
Noodle Fighter

### CODE REVIEW

**Comment by Virtual-Face** [comment]
And as everybody knows, a classic Koibot.

Koibot

**Comment by owocki** [comment]
@danlipert what do u think?

i think this is a good start!

**Comment by danlipert** [comment]
These are pretty cool - I love the watercolor style on the koi

**Comment by Virtual-Face** [comment]
Happy you liked them and thanks for the tip.
I have more ideas, do you want me to continue on more bots?

**Comment by owocki** [comment]
i think that having a few more kudos that are of Robots and Kaiju (monsters) fighting over the skyline of Tokyo/Osaka would be cool...

cc @GuistF @excerebrose

**Pull request merged**
