### PR TITLE
Add Bots -Android|Meditation|Github|Jack o Lantern

### PR DESCRIPTION
**Pull request by GuistF**
Gitcoin Bots3

### CODE REVIEW

**Comment by owocki** [comment]
@GuistF is my hero.  merging now

**Comment by GuistF** [comment]
thanks!!. I'll be here if you need to change something :)

**Comment by owocki** [comment]
request from the consensys NYC headquarters: "bot statue of liberty"

**Comment by GuistF** [comment]
Ok, I can do it, do I have to keep the Consensys or Gitcoin logo?

**Comment by owocki** [comment]
i'm not sure what consensys/gitcoin logo you're talking about

**Comment by GuistF** [comment]
Sorry! I mean, should I keep Gitcoin Logo with the same structure? Like in the others kudos

**Comment by GuistF** [comment]
Here is a sketch for you to evaluate,  I have added just some differences on face both.
statue_of_liberty

**Comment by owocki** [comment]
yes the same gitcoin logo / structure is good.

i like both statue of liberties!  can you raise a PR for them!?

**Comment by GuistF** [comment]
awesome, which one?

**Comment by GuistF** [comment]
hum ! ok

**Comment by owocki** [comment]
i think the one on the left is the best fit

**Comment by GuistF** [comment]
I already did the PR with the left Bot https://github.com/gitcoinco/creative/pull/109

**Pull request merged**
