### PR TITLE
Japanese style bots for Devcon V

### PR DESCRIPTION
**Pull request by excerebrose**
Hey @owocki, as requested I have made two new bots in the Japanese style,
if you like these let me know, I have got a few more ideas as well.

Attached here for reference..
japanese-bot-sketch
kendo-bot

for issue https://github.com/gitcoinco/web/issues/5111

### CODE REVIEW

**Comment by owocki** [comment]
thanks, are all artwork original / liscensed for us?

@danlipert knows japanese culture more than me, so curiuos what he thinks

**Comment by excerebrose** [comment]
Hey @owocki everything is original. 
I couldn't apply for work on the gitcoin bounty, so how do I proceed?

Happy to hear his thoughts.

**Comment by owocki** [comment]
hmm thats weird; i wonder if we should file a bug report.  you dont see 'start work' listed on the bounty?

as a workaround, i can just tip you directly to your gitcoin profile's ETH address :)

lets see what @danlipert says first tho

**Comment by excerebrose** [comment]
@owocki, nope no start work button either. Could it because of selecting the bounty type as "traditional"? 

I think someone mentioned this on the original issue as well https://github.com/gitcoinco/web/issues/5111#issuecomment-526894806

**Comment by owocki** [comment]
i just changed it to contest bounty type. try now?

**Comment by excerebrose** [comment]
@owocki Yup, the express interest button shows now.
Might be a possible bug if the bounty type was the issue, as far as I am aware traditional should still allow multiple parties to apply for work, and only 1 can be approved?

**Comment by owocki** [comment]
there was already someone approved; so thats why methinks

**Comment by excerebrose** [comment]
2 were approved, which kind of feels wrong too. maybe should move this to another thread, will have a look at what the model constraints are later in the day and report back.

**Comment by danlipert** [comment]
@excerebrose these look great! The kendo bot one with the Japanese sunburst might be a bit too "imperial" so I'd like to see one with a different background graphic - some folks have bad associations with it. From wikipedia:

"Due to the flag being used by the Imperial Japanese military and Japan's actions during World War II, it is offensive in East Asia, particularly in South Korea,[16][17][18] which was formerly ruled under Japan, and China.[19][20] Some World War II veteran groups in the United States have also campaigned against its use.[21] The symbol is associated with Japanese imperialism in the early 20th century[16][17][18][19][22][23][24] because of its use by Japan's military forces during that period."

**Comment by excerebrose** [comment]
@danlipert will make changes, thanks for the bit of info!

**Comment by excerebrose** [comment]
Hey @danlipert and @owocki 
Have updated the kendo bot, attached below for reference, let me know what you guys think.
kendo

**Comment by danlipert** [comment]
@excerebrose nice, looks great!

**Comment by excerebrose** [comment]
Thanks for the tip @owocki 
Do you want an artwork or two more for this? I've got some samples, but initial bounty restricted it to 2 artworks per person

**Comment by owocki** [comment]
sure lets do two more

**Pull request merged**
